import{a as b,S as L,i as x}from"./assets/vendor-09d7c26e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&r(m)}).observe(document,{childList:!0,subtree:!0});function c(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=c(e);fetch(e.href,s)}})();const v=b.create({baseURL:"https://pixabay.com/api/"});async function g(){const o={key:"3539379-d64fd5a5897018ff1512b690c",q:u,per_page:p,page:n,image_type:"photo",orientation:"horizontal",safesearch:"true"};return _(),(await v.get("",{params:o})).data}function h(o){if(o.hits.length===0)i("Sorry, there are no images matching your search query. Please try again!");else{const c=o.hits.map(r=>`<li class="gallery-item">
                <a class="gallery-link" href="${r.largeImageURL}">
                <img loading="lazy" class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
                </a>
                <div class="stats">
                    <p class="text"><span class="text__span">likes</span><br/>${r.likes}</p>
                    <p class="text"><span class="text__span">Views</span><br/>${r.views}</p>
                    <p class="text"><span class="text__span">Coments</span><br/>${r.comments}</p>
                    <p class="text"><span class="text__span">Dowloads</span><br/>${r.downloads}</p>
                </div>
            </li>`).join("");a.gallery.insertAdjacentHTML("beforeend",c),B.refresh()}}const B=new L(".gallery-link",{captionsData:"alt",captionDelay:250}),a={form:document.querySelector(".form"),searchInput:document.getElementById("searchInput"),searchBtn:document.querySelector("button"),loadBtn:document.querySelector(".load-more-button"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery")};let u="",n=1,p=15,f=0;y();d();function S(){return window.navigator.onLine}let l=!1;a.form.addEventListener("submit",async o=>{if(o.preventDefault(),n=1,a.gallery.innerHTML="",u=a.searchInput.value.trim(),l=!1,u!==""){if(!S()){i("Internet connection is lost. Please check your connection.");return}try{const t=await g(u,n);f=t.totalHits;const c=Math.ceil(f/p);h(t),y(),n>=c?d():w()}catch(t){console.log(t),i("An error occurred while fetching data."),d()}}else i("Empty field!"),d();a.form.reset()});a.loadBtn.addEventListener("click",async o=>{if(n*p>=f){l||(i("No more images to load."),l=!0);return}n+=1;try{const t=await g(u,n);y(),h(t),w();const r=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r.height*2,behavior:"smooth"});const e=Math.ceil(f/p);n>=e&&d()}catch(t){console.log(t),i("An error occurred while fetching data."),d()}});function i(o){o==="No more images to load."&&l||(x.error({title:"",message:o,position:"topRight",backgroundColor:"red"}),o==="No more images to load."&&(l=!0))}function y(){a.loader.style.display="none"}function _(){a.loader.style.display="block"}function d(){a.loadBtn.style.display="none"}function w(){a.loadBtn.style.display="block"}window.addEventListener("scroll",()=>{if(window.innerHeight+window.scrollY>=document.body.offsetHeight&&n*p>=f&&!l){i("No more images to load."),l=!0;return}});
//# sourceMappingURL=commonHelpers.js.map
