import{a as h,S as b,i as L}from"./assets/vendor-b2578120.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const p of r.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&o(p)}).observe(document,{childList:!0,subtree:!0});function l(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=l(e);fetch(e.href,r)}})();const w=h.create({baseURL:"https://pixabay.com/api/"});async function m(){const s={key:"3539379-d64fd5a5897018ff1512b690c",q:c,per_page:u,page:n,image_type:"photo",orientation:"horizontal",safesearch:"true"};return v(),(await w.get("",{params:s})).data}function y(s){if(s.hits.length===0)d("Sorry, there are no images matching your search query. Please try again!");else{const l=s.hits.map(o=>`<li class="gallery-item">
                <a class="gallery-link" href="${o.largeImageURL}">
                <img loading="lazy" class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
                </a>
                <div class="stats">
                    <p class="text"><span class="text__span">likes</span><br/>${o.likes}</p>
                    <p class="text"><span class="text__span">Views</span><br/>${o.views}</p>
                    <p class="text"><span class="text__span">Coments</span><br/>${o.comments}</p>
                    <p class="text"><span class="text__span">Dowloads</span><br/>${o.downloads}</p>
                </div>
            </li>`).join("");a.gallery.insertAdjacentHTML("beforeend",l),x.refresh()}}const x=new b(".gallery-link",{captionsData:"alt",captionDelay:250}),a={form:document.querySelector(".form"),searchInput:document.getElementById("searchInput"),searchBtn:document.querySelector("button"),loadBtn:document.querySelector(".load-more-button"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery")};let c="",n=1,u=30;f();i();a.form.addEventListener("submit",async s=>{if(s.preventDefault(),n=1,a.gallery.innerHTML="",c=a.searchInput.value.trim(),c!=="")try{const t=await m(c,n),l=Math.ceil(t.totalHits/u);y(t),f(),n>=l?i():g()}catch(t){console.log(t),d("An error occurred while fetching data."),i()}else d("Empty field!"),i();a.form.reset()});a.loadBtn.addEventListener("click",async s=>{n+=1;try{const t=await m(c,n);f(),y(t),g();const o=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o.height*2,behavior:"smooth"});const e=Math.ceil(t.totalHits/u);n>=e&&i()}catch(t){console.log(t),d("An error occurred while fetching data."),i()}});function d(s){L.error({title:"Error",message:s,position:"topRight",backgroundColor:"red"})}function f(){a.loader.style.display="none"}function v(){a.loader.style.display="block"}function i(){a.loadBtn.style.display="none"}function g(){a.loadBtn.style.display="block"}window.addEventListener("offline",()=>{alert("Втрата з'єднання з Інтернетом.")});
//# sourceMappingURL=commonHelpers.js.map
